While at it, fix inert-node-is-uneditable.html and inert-inlines.html.
Failed in Chrome and Firefox with:

  marionette_driver.errors.InvalidArgumentException: Expected 'x' ([object Number] 187.5) to be an Integer

Because of fractional widths. Round to deal with it.

Depends on D134964

Differential Revision: https://phabricator.services.mozilla.com/D134965

bugzilla-url: https://bugzilla.mozilla.org/show_bug.cgi?id=1743082
gecko-commit: d22ac03072b5751bdf62eb84773f2d9a409a73a8
gecko-reviewers: sefeng