Ensure we delete a session when closing the last window
Previously, we just set `session.session_id` to `None`; this is valid
if the browser has (correctly) deleted the session, but is very
problematic if it has not, as it means we no longer have the
`session_id` of the currently active session, and thus we can neither
use that session nor delete the session.

This copies what we do in the delete session tests, and both checks
that the session has been deleted, and then cleanly ends the session.

This should get the majority of WebDriver tests passing again on STP,
where everything after this test fails with:

webdriver.error.SessionNotCreatedException: session not created (500):
Could not create a session: The Safari instance is already paired with
another WebDriver session.