Replace edgedriver URL to fix Edge runs
Fixes: #53908

Currently, they are failing with this error:

```
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='msedgedriver.azureedge.net', port=443): Max retries exceeded with url: /140.0.3430.1/edgedriver_win32.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000176949CBC50>: Failed to resolve 'msedgedriver.azureedge.net' ([Errno 11001] getaddrinfo failed)"))
```

Looks like https://msedgedriver.azureedge.net was deprecated.

See:
- https://github.com/webdriverio-community/node-edgedriver/pull/501
- https://github.com/seleniumhq/selenium/issues/16073