Improve error message when virtualenv is missing
It can be challenging to properly configure systems to run the WPT CLI.
In recognition of this, this project maintains code paths that improve
error messages, helping users troubleshoot misconfigured systems.

Users may not have the `virtualenv` module installed, or they may have
it installed in such a way that is inaccessible during command-line
execution. Prior to the application of this patch, the error message
reported by the WPT CLI is somewhat cryptic:

    $ ./wpt run firefox
    Traceback (most recent call last):
      File "./wpt", line 4, in <module>
        from tools.wpt import wpt
      File "/home/vagrant/wpt/tools/wpt/wpt.py", line 10, in <module>
        from . import virtualenv
      File "/home/vagrant/wpt/tools/wpt/virtualenv.py", line 7, in <module>
        import pkg_resources
    ImportError: No module named pkg_resources

With this patch applied, a more helpful error is produced by a branch
which was previously created for this purpose:

    $ ./wpt run firefox
    Traceback (most recent call last):
      File "./wpt", line 5, in <module>
        wpt.main()
      File "/home/vagrant/wpt/tools/wpt/wpt.py", line 143, in main
        venv = setup_virtualenv(main_args.venv, main_args.skip_venv_setup, props)
      File "/home/vagrant/wpt/tools/wpt/wpt.py", line 117, in setup_virtualenv
        venv = virtualenv.Virtualenv(path, should_skip_setup)
      File "/home/vagrant/wpt/tools/wpt/virtualenv.py", line 30, in __init__
        raise ValueError("virtualenv must be installed and on the PATH")
    ValueError: virtualenv must be installed and on the PATH

Some commands do not rely on `virtualenv`, e.g. `wpt lint`. This change
also makes it possible to execute those commands when `virtualenv` is
not available.