[wpt-lint] Handle `FileNotFoundError` when `git` is not found (#39416)
`tools.lint.lint` is unimportable when `git` does not exist in the
`PATH`:

```
  File "C:\b\s\w\ir\third_party\blink\tools\blinkpy\tool\commands\lint_wpt.py", line 16, in <module>
    from tools.lint import lint as wptlint
  File "C:\b\s\w\ir\third_party\wpt_tools\wpt\tools\lint\__init__.py", line 1, in <module>
    from . import lint  # noqa: F401
  File "C:\b\s\w\ir\third_party\wpt_tools\wpt\tools\lint\lint.py", line 1135, in <module>
    subprocess.check_output(["git", "--version"])
  ...
  File "C:\b\s\w\ir\.task_template_vpython_cache\vpython\store\cpython-e6tenrlsesftvg6k08ajgkk7b4\contents\bin\Lib\subprocess.py", line 1311, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```