Met AttributeError due to screenshot returns None (#34901)
* Met AttributeError due to screenshot returns None

Check and raise ValueError in such situation. The exception will be processed later.

Stack trace as below:
File "/b/s/w/ir/third_party/wpt_tools/wpt/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 405, in run_func
    self.result = True, self.func(self.protocol, self.url, self.timeout)
File "/b/s/w/ir/third_party/wpt_tools/wpt/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 620, in _screenshot
    if screenshot.startswith("data:image/png;base64,"):
AttributeError: 'NoneType' object has no attribute 'startswith'