Met AttributeError due to screenshot returns None
Stack trace as belw:
File "/b/s/w/ir/third_party/wpt_tools/wpt/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 405, in run_func
    self.result = True, self.func(self.protocol, self.url, self.timeout)
File "/b/s/w/ir/third_party/wpt_tools/wpt/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 620, in _screenshot
    if screenshot.startswith("data:image/png;base64,"):
AttributeError: 'NoneType' object has no attribute 'startswith'