Make wptrun fail correctly when certutil not found
This change makes wptrun correctly handle the case where it can’t find
the certutil binary.

Without this change you end up with the value of `path` being `None`
when it reaches this part of the tools/browserutils/browser.py code:

    if os.path.splitdrive(path)[1].split(os.path.sep) == ["", "Windows", "system32", "certutil.exe"]:

... which results in:

    AttributeError: 'NoneType' object has no attribute 'split'

So this change just early-returns `None` from there if `path` is `None`.