Fix Safari artifact names
With the unified workflow, we don't actually need to specify the
wildcard, as this will just lead to errors like:

> Error: The artifact name is not valid:
> safari-technology-preview-results-*-6. Contains the following
> character: Asterisk *

e.g., in
https://github.com/web-platform-tests/wpt/actions/runs/11410328782/job/31752427266